server:
  port: 8081
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

spring:
  application:
    name: ms-inventory-products

  datasource:
      url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/buscador
      username: postgres.nfmocsiltmwjrdvjqgos
      password: F.uG7PvpHrH6.CW
      driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-inventory-products
